### PR TITLE
Source install

### PR DESCRIPTION
**Pull request by thoutenbos**
- Rebased https://github.com/hw-cookbooks/stunnel/pull/13
- Added required ssl-devel

### CODE REVIEW

**Comment by jkamke** [comment]
I tried this out and noticed that the '/etc/stunnel/' directory is missing which causes failure.

**Comment by martinisoft** [comment]
Hi @thoutenbos  

Thanks for sending in this pull request. DNSimple has adopted this cookbook from Heavy Water and I've cleaned up the master branch to get the test suites working correctly again. If you would like to get these changes into master, please rebase against master and we can look at merging this in once again.

**Comment by thoutenbos** [comment]
Hi @martinisoft 

Thanks for taking it over and bringing it back to life! Rebased against your master, please review.

Best,
Thijs

**Comment by thoutenbos** [comment]
Sure, should be good to go now

**Comment by martinisoft** [comment]
This looks great! Thank you for the contribution @thoutenbos :+1:

**Pull request merged**
