### PR TITLE
Expose SSL ciphers option

### PR DESCRIPTION
**Pull request by thoutenbos**

### CODE REVIEW

**Comment by jhmartin** [comment]
Can this be merged?

**Comment by martinisoft** [comment]
Hi @thoutenbos  

Thanks for sending in this pull request. DNSimple has adopted this cookbook from Heavy Water and I've cleaned up the master branch to get the test suites working correctly again. If you would like to get these changes into master, please rebase against master and we can look at merging this in once again.

**Comment by thoutenbos** [comment]
Also rebased!

**Comment by martinisoft** [comment]
Thank you @thoutenbos we'll get this out in the next release :+1:

**Pull request merged**
